apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: rust-k8s-demo
build:
  artifacts:
    - image: databaseservice
      context: databaseservice
      docker:
        dockerfile: Dockerfile
    - image: frontendservice
      context: frontendservice
      docker:
        dockerfile: Dockerfile
    - image: quotationservice
      context: quotationservice
      docker:
        dockerfile: Dockerfile
  local: {}
manifests:
  rawYaml:
    - manifests/gateway.yaml
    - manifests/postgres-tls.yaml
    - manifests/databaseservice.yaml
    - manifests/frontendservice.yaml
    - manifests/quotationservice.yaml
    - manifests/redis.yaml
