[package]
name = "quotation-server"
version = "0.1.0"
authors = ["Pradip Caulagi <caulagi@gmail.com>"]
edition = "2021"

license = "MIT"

[[bin]]
name = "quotation-server"
path = "src/main.rs"

[dependencies]
bytes = "1.11.1"
metrics = "0.24.6"
metrics-exporter-prometheus = { version = "0.18.3", default-features = false, features = ["http-listener"] }
prost = "0.14.3"
prost-types = "0.14.3"
rand = "0.10"
redis = { version = "1.7", features = ["tokio-comp", "connection-manager"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
rustls-pki-types = { version = "1", features = ["std"] }
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.17"
tokio-postgres-rustls = "0.14"
tonic = "0.14.5"
tonic-prost = "0.14.5"
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["default", "env-filter"]}
tracing-futures = "0.2.5"
tracing-attributes = "0.1.31"

[build-dependencies]
tonic-prost-build = "0.14.5"
